### ISSUE TITLE
Saving error

### ISSUE THREAD

**Issue by 25Adam25** [Arnuh/HaSuite#7] opened 2024-01-26 19:23 UTC
I tried adding a rope to a map and then save it cause with HaCreator there's the rope saving issue.
No files that I know of are in use.

![PheCreator_PEU4jwZqzd](https://github.com/Arnuh/HaSuite/assets/58709937/ec9216dd-16bd-4db8-89a5-bfdf0d111564)
![PheCreator_bVbFn0z491](https://github.com/Arnuh/HaSuite/assets/58709937/59cad1f3-1243-469d-9dfa-09e030195b33)

**Comment by Arnuh** [comment] 2024-01-28 04:28
Yeah I've had related issues with internal testing but I was personally able to fix it by just.. running one of my other tools and replacing the Map.wz, and it magically went away ever since. For my other tester, it was not like that.

Something is still holding the file lock despite what should be at this state, not locked, but it is only happening in weird cases.

This is assuming that map.wz was still saved, it was just unable to rename it from the backup file to Map.wz

**Comment by 25Adam25** [comment] 2024-01-28 23:28
If you add a way to save a map by saving just the XML of the map, could it possibly fix the issue somewhat?
Basically like koolk's map editor, I find it very useful.

**Comment by Arnuh** [comment] 2024-01-29 02:01
Saving already does a "backup" xml

**Comment by Arnuh** [comment] 2024-02-05 07:17
Try this, build from latest master

[HaSuite-x64-issue-7-fix.zip](https://github.com/Arnuh/HaSuite/files/14161708/HaSuite-x64-issue-7-fix.zip)

**Comment by 25Adam25** [comment] 2024-02-07 19:39
> Try this, built from latest master
> 
> SHA256: c1bbf884d033bce0f35df8a67a841a5c34fdc0f64eb3cadf919b026d8cc92221
> 
> [HaSuite-x64-issue-7-fix.zip](https://github.com/Arnuh/HaSuite/files/14161708/HaSuite-x64-issue-7-fix.zip)

There's a different error now:

`System.NullReferenceException: Object reference not set to an instance of an object.
   at MapleLib.WzLib.WzProperties.WzPngProperty.Compress(Byte[] decompressedBuffer)
   at MapleLib.WzLib.WzProperties.WzPngProperty.CompressPng(Bitmap bmp)
   at HaCreator.Wz.MapSaver.SaveMiniMap() in S:\Projects\MapleStory\Harepacker-resurrected\HaCreator\Wz\MapSaver.cs:line 137
   at HaCreator.Wz.MapSaver.SaveMapImage() in S:\Projects\MapleStory\Harepacker-resurrected\HaCreator\Wz\MapSaver.cs:line 702
   at HaCreator.GUI.Save.saveButton_Click(Object sender, EventArgs e) in S:\Projects\MapleStory\Harepacker-resurrected\HaCreator\GUI\Save.cs:line 123
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)`

**Comment by Arnuh** [comment] 2024-02-08 00:26
Weird, altho master branch doesn't have a proper fix for it, a temp fix has been on master for awhile now and that error isn't possible. I'm also unable to reproduce with the build I provided above.

**Comment by Arnuh** [comment] 2024-03-07 01:25
I'm considering this fixed with the 2.0-beta.1 release I've done

**Closed by Arnuh** 2024-03-07 01:25 UTC
